apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
  name: integrasjonspunkt
spec:
  selector:
    app: integrasjonspunkt
  ports:
  - name: "tcp9094"
    protocol: TCP
    port: 9094
    targetPort: 9094
  type: LoadBalancer
  loadBalancerIP: 35.228.172.189
  loadBalancerSourceRanges:
  - 40.115.18.169/32
  - 40.68.26.84/32
  - 213.236.148.83/32
  - 195.159.162.32/27
  - 195.159.248.98/32
