#!/command/with-contenv bash

cd ${APP_DIR}
# Korrigerer integrasjonspunktets port dersom porten endres i Azure Web App-konfig
if [ -n "${PORT+set}" ]; then
    export SERVER_PORT=$PORT
fi
unset JAVA_TOOL_OPTIONS
runner=www-data
if [ $SERVER_PORT -le 1024 ]; then
    # Må kjøre som root med SERVER_PORT < 1024
    runner=root
fi
exec s6-setuidgid $runner java ${JAVA_OPTS} -jar app.jar
