# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dibk-ip-staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dibknoe.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8a22ae28be494dd8b1489a496e05a1f9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7551de1f791e469ebefd0bdcb1381f7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dibknoe.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a22ae28be494dd8b1489a496e05a1f9 }}/app/integrasjonspunkt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dibk-ip-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_47203314638d4f4dbf6b8e6c4bf67799 }}
        images: 'dibknoe.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a22ae28be494dd8b1489a496e05a1f9 }}/app/integrasjonspunkt:${{ github.sha }}'