name: Prime certs-cache

on:
  workflow_dispatch:

jobs:
  prime:
    runs-on: self-hosted
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Henter inn CA-sertifikater fra cache
      uses: actions/cache@v4
      id: ca-certs-cache
      env:
        cache-name: ca-certs-cache
      with:
        path: docker/trustcerts
        key: ${{env.cache-name}}-${{ hashFiles('docker/trustcerts/**.cer') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Henter inn CA-sertifikater uten cache
      if: steps.ca-certs-cache.outputs.cache-hit != 'true'
      run: |
        curl -Lso docker/trustcerts/BuyPassClass3RootCA.cer "https://github.com/felleslosninger/docs/raw/gh-pages/resources/begrep/sikkerDigitalPost/sikkerhet/sertifikater/prod/BPClass3RootCA.cer"
        curl -Lso docker/trustcerts/CommfidesClass3RootCA.cer "https://github.com/felleslosninger/docs/raw/gh-pages/resources/begrep/sikkerDigitalPost/sikkerhet/sertifikater/prod/cpn%20rootca%20sha256%20class%203.crt"
        openssl s_client -connect ${{vars.ALTINN_HOST}}:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > docker/trustcerts/${{vars.ALTINN_HOST}}.cer
    
    - name: Tester certs
      run: ls -lah docker/trustcerts/
