name: test Azure login action

on:
    workflow_dispatch:

jobs:
    login:
        runs-on: [self-hosted, macOS]
        environment: production
        steps:
            - name: Azure CLI login
              run: |
                echo "${{ secrets.AZURE_SP_CERT }}" > sp.cert
                az login --service-principal -u ${{ vars.AZURE_SP_ID }} -p ./sp.cert --tenant ${{ vars.AZURE_TENANT_ID }}
            - name: Henter virksomhetssertifikat fra Key Vault
              run: |
                az keyvault secret download --encoding base64 --name ${{ vars.AZURE_KV_CERT_NAME }} --file vs.p12 --vault-name ${{ vars.KEYVAULT_NAME }}

